# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tdd_testing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  # Pods for tdd_testing

  target 'tdd_testingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
